### ISSUE TITLE
Note that such proxy may have issues in some edge cases.

### ISSUE THREAD

**Issue by vi** [ZekeMedley/tcp-proxy#2]
Main discussion: https://github.com/tokio-rs/tokio/discussions/3173

It may fail to correctly propagate a suddenly disconnected client in a backpressure scenario.

I've created a dedicated tool to check TCP proxies: https://github.com/vi/tcptunnelchecker and this proxy fails the check (the tool freezes).

Note that implementing a TCP proxy fully correctly may be impossible with today's Tokio. In any case this proxy project should define scope, limitations and known bugs.

**Comment by 0xekez** [comment]
Thanks for pointing this out and testing the proxy. I'm not terribly surprised that there are issues with this - the goal is more educational than for use in production. I'll add some info to the readme to make that more clear :)
